# Generated by Django 4.1.5 on 2023-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
    ]
