# Generated by Django 4.1.5 on 2023-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_inquiry_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('city_id', models.CharField(max_length=20)),
                ('area_id', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('reg_date', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('role_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
