# Generated by Django 4.1.5 on 2023-02-15 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0006_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('reg_date', models.DateField()),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.area')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
