# Generated by Django 4.1.5 on 2023-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
