# Generated by Django 4.1.5 on 2023-02-16 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0009_alter_customers_area_alter_customers_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('reg_date', models.DateField()),
                ('state', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('area', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
    ]
