# Generated by Django 4.1.5 on 2023-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='don_category',
            field=models.CharField(max_length=30),
        ),
    ]
