# Generated by Django 4.1.5 on 2023-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_alter_donation_don_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='area',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='contact_no',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='contact_person',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
