# Generated by Django 4.1.5 on 2023-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_donation_area_donation_city_donation_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='area',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='customers',
            name='state',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='area',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='city',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='state',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
