# Generated by Django 4.1.5 on 2023-02-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0016_alter_customers_area_alter_customers_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol_acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_dt', models.DateField()),
                ('received_remarks', models.TextField()),
                ('delivered_dt', models.DateField()),
                ('delivered_remarks', models.TextField()),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.donation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vol_acceptance',
            },
        ),
    ]
