# Generated by Django 4.1.5 on 2023-02-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_vol_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.area'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city'),
        ),
    ]
