# Generated by Django 4.1.5 on 2023-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0019_remove_donation_area_remove_donation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='area',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
