# Generated by Django 4.1.5 on 2023-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_remove_donation_area_remove_donation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=None),
        ),
    ]
