# Generated by Django 4.1.5 on 2023-02-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0023_donate_remove_vol_acceptance_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city',
        ),
        migrations.RemoveField(
            model_name='area',
            name='state',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.RemoveField(
            model_name='vol_acceptance',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='vol_acceptance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Vol_acceptance',
        ),
        migrations.DeleteModel(
            name='Volunteers',
        ),
    ]
