# Generated by Django 4.1.5 on 2023-02-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myadmin', '0024_remove_area_city_remove_area_state_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('don_category', models.CharField(max_length=30)),
                ('contact_person', models.CharField(default=None, max_length=30)),
                ('contact_no', models.CharField(default=None, max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(default=None, max_length=30)),
                ('donation_date', models.DateField(default=None)),
                ('area_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donate',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contact', models.CharField(default=None, max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('reg_date', models.DateField()),
                ('state', models.CharField(default=None, max_length=10)),
                ('city', models.CharField(default=None, max_length=10)),
                ('area', models.CharField(default=None, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
        migrations.CreateModel(
            name='Vol_acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_dt', models.DateField()),
                ('received_remarks', models.TextField()),
                ('delivered_dt', models.DateField()),
                ('delivered_remarks', models.TextField()),
                ('donate', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.donate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vol_acceptance',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('reg_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('contact', models.CharField(default=None, max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('reg_date', models.DateField()),
                ('state', models.CharField(default=None, max_length=10)),
                ('city', models.CharField(default=None, max_length=10)),
                ('area', models.CharField(default=None, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city'),
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.state'),
        ),
    ]
