# Generated by Django 4.1.7 on 2023-02-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0025_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='area_id',
            new_name='area',
        ),
    ]
