# Generated by Django 4.1.7 on 2023-02-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0026_rename_area_id_donate_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city'),
        ),
    ]
