# Generated by Django 4.1.7 on 2023-02-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0030_alter_donate_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.area'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city'),
        ),
    ]
