# Generated by Django 4.1.5 on 2023-02-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0031_alter_donate_area_alter_donate_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol_acceptance',
            name='delivered_dt',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='vol_acceptance',
            name='delivered_remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vol_acceptance',
            name='donate',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='myadmin.donate'),
        ),
        migrations.AlterField(
            model_name='vol_acceptance',
            name='received_dt',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='vol_acceptance',
            name='received_remarks',
            field=models.TextField(default=''),
        ),
    ]
