# Generated by Django 4.1.5 on 2023-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0036_u_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_events',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
