# Generated by Django 4.1.5 on 2023-03-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0039_alter_feedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
